/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackgroundVideo: typeof import('./components/layout/BackgroundVideo.vue')['default']
    ButtonSearch: typeof import('./components/inputs/ButtonSearch.vue')['default']
    IconLogo: typeof import('./components/icons/IconLogo.vue')['default']
    IconSearchAnimated: typeof import('./components/icons/IconSearchAnimated.vue')['default']
    IconSpinner: typeof import('./components/icons/IconSpinner.vue')['default']
    LoadingScreen: typeof import('./components/layout/LoadingScreen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBarSearch: typeof import('./components/layout/TopBarSearch.vue')['default']
  }
}
